name: phoenix_single
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:
  http: ^1.2.0
  ansicolor: ^2.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
